### ISSUE TITLE
Cannot start demo

### ISSUE THREAD

**Issue by webspin** [gatteo/react-jitsi#28]
I can't make the demo from https://gatteo.github.io/react-jitsi/ work:

Failed to execute pre call test -  {status: "authError", message: "Authenticator: Invalid token"}

**Comment by webspin** [comment]
And after that:
conference.js:2640 Uncaught (in promise) TypeError: Cannot set property 'deviceId' of null
    at conference.js:2640

**Comment by Angus-McLean** [comment]
Perhaps relates to this? https://github.com/jitsi/jitsi-meet/pull/6955

**Comment by jim-simpletire** [comment]
It looks like the jitsi-meet issue was resolved and merged on June 8th. Is there a dependency on that library that needs to be updated in this repo?

**Comment by shubham7298** [comment]
The demo is not working, https://gatteo.github.io/react-jitsi/ keeps on loading after entering the details.
Is it resolved?
What's wrong?

**Comment by dacopan** [comment]
solved in https://github.com/gatteo/react-jitsi/issues/14

**Comment by jim-simpletire** [comment]
@dacopan The discussion in #14 suggests a fix but no PR was created. However the demo application still does not work at https://gatteo.github.io/react-jitsi/ . Does the fix discussed from #14 need to be applied to the demo application code to get it to work?

**Comment by jim-simpletire** [comment]
FYI - even though the demo doesn't work, the component does if you add `config={{prejoinPageEnabled: false}}` to the Jitsi tag, like this:
`<Jitsi config={{prejoinPageEnabled: false}} />`

**Comment by AjeelAhmed1998** [comment]
@jim-simpletire I tried your solution and it works now, thanks a ton! Will you be creating a PR for this?

**Comment by jim-simpletire** [comment]
@AjeelAhmed1998 Yeah, I can submit PR to add that to the Jitsi tag.

**Comment by idimensionz** [comment]
I've created a PR to add that property to the Jitsi tag in the demo. https://github.com/gatteo/react-jitsi/pull/30
